### ISSUE TITLE
Where's the code?

### ISSUE THREAD

**Issue by michaelleerilee** [SpatioTemporal/STARELite#1]
I'd like to try this out, but can't find any code?

Also it's good to push intermediate code development states to an appropriate branch just in case a computer or storage system fails.

**Comment by NiklasPhabian** [comment]
AI; yeah. I had it all just synced with Dropbox!
I think to get you started, it might be the easiest to load the STARE index values as text and then use encode_stareblob() to convert them into stareblobs. otherwise you'll have to toy around with spatialite, which sometimes can be a can of worms.

The jupyter notebook in examples/ (very unstructured) gives some idea on how to load spatialite data e.g. from shapefiles or geopackages via geopandas
